{{- if .Values.tracepointApi.autoscaling.enabled }}
{{- $apiVersion := include "deep.hpa.apiVersion" . -}}
apiVersion: {{ $apiVersion }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "deep.resourceName" (dict "ctx" . "component" "tracepoint-api") }}
  labels:
    {{- include "deep.labels" (dict "ctx" . "component" "tracepoint-api") | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "deep.resourceName" (dict "ctx" . "component" "tracepoint-api") }}
  minReplicas: {{ .Values.tracepointApi.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.tracepointApi.autoscaling.maxReplicas }}
  {{- with .Values.tracepointApi.autoscaling.behavior }}
  behavior:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  metrics:
  {{- with .Values.tracepointApi.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        {{- if (eq $apiVersion "autoscaling/v2") }}
        target:
          type: Utilization
          averageUtilization: {{ . }}
        {{- else }}
        targetAverageUtilization: {{ . }}
        {{- end }}
  {{- end }}
  {{- with .Values.tracepointApi.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        {{- if (eq $apiVersion "autoscaling/v2") }}
        target:
          type: Utilization
          averageUtilization: {{ . }}
        {{- else }}
        targetAverageUtilization: {{ . }}
        {{- end }}
  {{- end }}
{{- end }}
