{{ $dict := dict "ctx" . "component" "compactor" "memberlist" true }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "deep.resourceName" $dict }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "deep.labels" $dict | nindent 4 }}
  {{- with .Values.compactor.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  minReadySeconds: 10
  replicas: {{ .Values.compactor.replicas }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      {{- include "deep.selectorLabels" $dict | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        {{- include "deep.podLabels" $dict | nindent 8 }}
        {{- with .Values.deep.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.compactor.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-deep.yaml") . | sha256sum }}
        {{- with .Values.deep.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.compactor.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if or (.Values.compactor.priorityClassName) (.Values.global.priorityClassName) }}
      priorityClassName: {{ default .Values.compactor.priorityClassName .Values.global.priorityClassName }}
      {{- end }}
      serviceAccountName: {{ include "deep.serviceAccountName" . }}
      {{- with .Values.deep.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      enableServiceLinks: false
      {{- include "deep.compactorImagePullSecrets" . | nindent 6 -}}
      {{- with .Values.compactor.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - args:
            - -target=compactor
            - -config.file=/conf/deep.yaml
            - -mem-ballast-size-mbs=1024
            {{- with .Values.compactor.extraArgs }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          image: {{ include "deep.imageReference" $dict }}
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          name: compactor
          ports:
            - containerPort: 3100
              name: http-metrics
            - containerPort: 7946
              name: http-memberlist
          {{- with .Values.compactor.extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.compactor.extraEnvFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.compactor.resources | nindent 12 }}
          {{- with .Values.deep.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /conf
              name: config
            - mountPath: /runtime-config
              name: runtime-config
            - mountPath: /var/deep
              name: deep-compactor-store
            {{- with .Values.compactor.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      terminationGracePeriodSeconds: {{ .Values.compactor.terminationGracePeriodSeconds }}
      {{- if ge (.Capabilities.KubeVersion.Minor|int) 19 }}
      {{- with .Values.compactor.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- tpl . $ | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- with .Values.compactor.affinity }}
      affinity:
        {{- tpl . $ | nindent 8 }}
      {{- end }}
      {{- with or .Values.compactor.nodeSelector .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.compactor.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.compactor.dnsConfigOverides.enabled }}
      {{- with .Values.compactor.dnsConfigOverides.dnsConfig }}
      dnsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      volumes:
        - name: config
          {{- include "deep.configVolume" . | nindent 10 }}
        - name: runtime-config
          {{- include "deep.runtimeVolume" . | nindent 10 }}
        - name: deep-compactor-store
          emptyDir: {}
        {{- with .Values.compactor.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
