{{ $dict := dict "ctx" . "component" "distributor" "memberlist" true }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "deep.resourceName" $dict }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "deep.labels" $dict | nindent 4 }}
  {{- with .Values.distributor.deployment.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  minReadySeconds: 10
{{- if not .Values.distributor.autoscaling.enabled }}
  replicas: {{ .Values.distributor.replicas }}
{{- end }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      {{- include "deep.selectorLabels" $dict | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "deep.podLabels" $dict | nindent 8 }}
        {{- with .Values.deep.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.distributor.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-deep.yaml") . | sha256sum }}
        {{- with .Values.deep.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.distributor.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if or (.Values.distributor.priorityClassName) (.Values.global.priorityClassName) }}
      priorityClassName: {{ default .Values.distributor.priorityClassName .Values.global.priorityClassName }}
      {{- end }}
      serviceAccountName: {{ include "deep.serviceAccountName" . }}
      {{- with .Values.deep.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      enableServiceLinks: false
      {{- include "deep.distributorImagePullSecrets" . | nindent 6 -}}
      {{- with .Values.distributor.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - args:
            - -target=distributor
            - -config.file=/conf/deep.yaml
            - -mem-ballast-size-mbs=1024
            {{- with .Values.distributor.extraArgs }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          image: {{ include "deep.imageReference" $dict }}
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          name: distributor
          ports:
            - containerPort: 3100
              name: http-metrics
            - containerPort: 7946
              name: http-memberlist
              protocol: TCP
            {{- if .Values.distributor.config.receivers.deep.enabled }}
            - containerPort: 43315
              name: deep
              protocol: TCP
            {{- end }}
          {{- with .Values.distributor.extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.distributor.extraEnvFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          readinessProbe:
            {{- toYaml .Values.deep.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.distributor.resources | nindent 12 }}
          {{- with .Values.deep.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /conf
              name: config
            - mountPath: /runtime-config
              name: runtime-config
            - mountPath: /var/deep
              name: deep-distributor-store
            {{- with .Values.distributor.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      terminationGracePeriodSeconds: {{ .Values.distributor.terminationGracePeriodSeconds }}
      {{- if ge (.Capabilities.KubeVersion.Minor|int) 19 }}
      {{- with .Values.distributor.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- tpl . $ | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- with .Values.distributor.affinity }}
      affinity:
        {{- tpl . $ | nindent 8 }}
      {{- end }}
      {{- with or .Values.distributor.nodeSelector .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.distributor.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          {{- include "deep.configVolume" . | nindent 10 }}
        - name: runtime-config
          {{- include "deep.runtimeVolume" . | nindent 10 }}
        - name: deep-distributor-store
          emptyDir: {}
        {{- with .Values.distributor.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}