{{- $dict := dict "ctx" . "component" "distributor" true }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "deep.resourceName" $dict }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "deep.labels" $dict | nindent 4 }}
  {{- with .Values.distributor.service.labels }}
    {{- toYaml . | nindent 4}}
  {{- end}}
  {{- with .Values.distributor.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4}}
  {{- end}}
spec:
  type: {{ .Values.distributor.service.type }}
  {{- if eq .Values.distributor.service.type "LoadBalancer" }}
  {{- if .Values.distributor.service.loadBalancerIP}}
  loadBalancerIP: {{ .Values.distributor.service.loadBalancerIP }}
  {{- end}}
  {{- with .Values.distributor.service.loadBalancerSourceRanges}}
  loadBalancerSourceRanges:
    {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  ports:
    - name: http-metrics
      port: 3100
      targetPort: http-metrics
    - name: grpc
      port: 9095
      protocol: TCP
      targetPort: 9095
      {{- if .Values.distributor.appProtocol.grpc }}
      appProtocol: {{ .Values.distributor.appProtocol.grpc }}
      {{- end }}
    {{- if .Values.distributor.config.receivers.deep.enabled }}
    - name: distributor-deep
      port: 43315
      protocol: TCP
      targetPort: deep
      {{- if .Values.distributor.appProtocol.grpc }}
      appProtocol: {{ .Values.distributor.appProtocol.grpc }}
      {{- end }}
    {{- end }}
  selector:
    {{- include "deep.selectorLabels" $dict | nindent 4 }}