apiVersion: v1
kind: Service
metadata:
  name: {{ include "deep.resourceName" (dict "ctx" . "component" "gossip-ring") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "deep.labels" (dict "ctx" . "component" "gossip-ring") | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: gossip-ring
      port: 7946
      protocol: TCP
      targetPort: http-memberlist
      {{- if .Values.deep.memberlist.appProtocol }}
      appProtocol: {{ .Values.deep.memberlist.appProtocol }}
      {{- end }}
  publishNotReadyAddresses: true
  selector:
    {{- include "deep.gossipRingSelectorLabels" (dict "ctx" .) | nindent 4 }}
