{{- $dict := dict "ctx" . "component" "ingester" true }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "deep.resourceName" $dict }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "deep.labels" $dict | nindent 4 }}
  {{- with .Values.ingester.service.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
    - name: http-metrics
      port: 3100
      protocol: TCP
      targetPort: 3100
    - name: grpc
      port: 9095
      protocol: TCP
      targetPort: 9095
      {{- if .Values.ingester.appProtocol.grpc }}
      appProtocol: {{ .Values.ingester.appProtocol.grpc }}
      {{- end }}
  selector:
    {{- include "deep.selectorLabels" $dict | nindent 4 }}
