{{ $dict := dict "ctx" . "component" "ingester" "memberlist" true }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "deep.resourceName" $dict }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "deep.labels" $dict | nindent 4 }}
  {{- with .Values.ingester.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if not .Values.ingester.autoscaling.enabled }}
  replicas: {{ .Values.ingester.replicas }}
{{- end }}
  selector:
    matchLabels:
      {{- include "deep.selectorLabels" $dict | nindent 6}}
  serviceName: ingester
  podManagementPolicy: Parallel
  updateStrategy:
    rollingUpdate:
      partition: 0
  template:
    metadata:
      labels:
        {{- include "deep.podLabels" $dict | nindent 8 }}
        {{- with .Values.deep.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.ingester.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-deep.yaml") . | sha256sum }}
        {{- with .Values.deep.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.ingester.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if or (.Values.ingester.priorityClassName) (.Values.global.priorityClassName) }}
      priorityClassName: {{ default .Values.ingester.priorityClassName .Values.global.priorityClassName }}
      {{- end }}
      serviceAccountName: {{ include "deep.serviceAccountName" . }}
      {{- with .Values.deep.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      enableServiceLinks: false
      {{- include "deep.ingesterImagePullSecrets" . | nindent 6 -}}
      {{- with .Values.ingester.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - args:
            - -target=ingester
            - -config.file=/conf/deep.yaml
            - -mem-ballast-size-mbs=1024
            {{- with .Values.ingester.extraArgs }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          image: {{ include "deep.imageReference" $dict }}
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          name: ingester
          ports:
            - name: grpc
              containerPort: 9095
            - name: http-memberlist
              containerPort: 7946
            - name: http-metrics
              containerPort: 3100
          {{- with .Values.ingester.extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.ingester.extraEnvFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          readinessProbe:
            {{- toYaml .Values.deep.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.ingester.resources | nindent 12 }}
          {{- with .Values.deep.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /conf
              name: config
            - mountPath: /runtime-config
              name: runtime-config
            - mountPath: /var/deep
              name: data
            {{- with .Values.ingester.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      terminationGracePeriodSeconds: {{ .Values.ingester.terminationGracePeriodSeconds }}
      {{- if ge (.Capabilities.KubeVersion.Minor|int) 19 }}
      {{- with .Values.ingester.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- tpl . $ | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- with .Values.ingester.affinity }}
      affinity:
        {{- tpl . $ | nindent 8 }}
      {{- end }}
      {{- with or .Values.ingester.nodeSelector .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ingester.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          {{- include "deep.configVolume" . | nindent 10 }}
        - name: runtime-config
          {{- include "deep.runtimeVolume" . | nindent 10 }}
        {{- with .Values.ingester.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
  {{- if not .Values.ingester.persistence.enabled }}
        - name: data
          emptyDir: {}
  {{- else if .Values.ingester.persistence.inMemory }}
        - name: data
        {{- if .Values.ingester.persistence.inMemory }}
          emptyDir:
            medium: Memory
        {{- end }}
        {{- if .Values.ingester.persistence.size }}
            sizeLimit: {{ .Values.ingester.persistence.size }}
        {{- end }}
  {{- else }}
  volumeClaimTemplates:
    - metadata:
        {{- with .Values.ingester.persistence.annotations }}
        annotations:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        {{- with .Values.ingester.persistence.storageClass }}
        storageClassName: {{ if (eq "-" .) }}""{{ else }}{{ . }}{{ end }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.ingester.persistence.size | quote }}
  {{- end }}
