apiVersion: v1
kind: Service
metadata:
  name: {{ include "deep.resourceName" (dict "ctx" . "component" "query-frontend-discovery") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "deep.labels" (dict "ctx" . "component" "query-frontend") | nindent 4 }}
    {{- with .Values.queryFrontend.serviceDiscovery.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.queryFrontend.serviceDiscovery.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: 3100
      targetPort: 3100
    - name: grpc
      port: 9095
      protocol: TCP
      targetPort: 9095
      {{- if .Values.queryFrontend.appProtocol.grpc }}
      appProtocol: {{ .Values.queryFrontend.appProtocol.grpc }}
      {{- end }}
    - name: grpclb
      port: 9096
      protocol: TCP
      targetPort: grpc
      {{- if .Values.queryFrontend.appProtocol.grpc }}
      appProtocol: {{ .Values.queryFrontend.appProtocol.grpc }}
      {{- end }}
  publishNotReadyAddresses: true
  selector:
    {{- include "deep.selectorLabels" (dict "ctx" . "component" "query-frontend") | nindent 4 }}
