{{- if not .Values.overrides.useExternalConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ tpl .Values.overrides.externalRuntimeConfigName . }}
  labels:
    {{- include "deep.labels" (dict "ctx" .) | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
data:
  overrides.yaml: |
    {{ include "deep.overridesConfig" . | nindent 4 }}
{{- end }}
