{{- if .Values.service.enabled -}}
{{- if .Values.service.ingress.enabled -}}
{{- $ingressApiIsStable := eq (include "deep.ingress.isStable" .) "true" -}}
{{- $ingressSupportsIngressClassName := eq (include "deep.ingress.supportsIngressClassName" .) "true" -}}
{{- $ingressSupportsPathType := eq (include "deep.ingress.supportsPathType" .) "true" -}}
apiVersion: {{ include "deep.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ template "deep.fullname" . }}
  labels:
    {{- include "deep.labels" (dict "ctx" . "component" "gateway") | nindent 4 }}
  {{- with .Values.service.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and $ingressSupportsIngressClassName .Values.service.ingress.ingressClassName }}
  ingressClassName: {{ .Values.service.ingress.ingressClassName }}
  {{- end -}}
  {{- if .Values.service.ingress.tls }}
  tls:
    {{- range .Values.service.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      {{- with .secretName }}
      secretName: {{ . }}
      {{- end }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.service.ingress.hosts }}
    {{- $paths := coalesce .paths $.Values.service.ingress.defaultPaths}}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range $paths }}
          - path: {{ .path }}
            {{- if $ingressSupportsPathType }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if $ingressApiIsStable }}
              service:
                name: {{ template "deep.fullname" $ }}
                port:
                  number: {{ .port }}
              {{- else }}
              serviceName: {{ template "deep.fullname" $ }}
              servicePort: {{ .port }}}
              {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
{{- end }}
