{{- if .Values.monitoring.rules.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "deep.fullname" $ }}-rules
  namespace: {{ default $.Release.Namespace $.Values.monitoring.rules.namespace }}
  {{- with $.Values.monitoring.rules.annotations }}
  annotations:
    {{- toYaml . | nindent 4 -}}
  {{- end }}
  labels:
      {{- include "deep.labels" (dict "ctx" $) | nindent 4 }}
      {{- with $.Values.monitoring.rules.labels }}
      {{- toYaml . | nindent 4 }}
      {{- end}}
spec:
  groups:
    - name: deep.rules
      rules:
        {{ range .Values.monitoring.rules.rules }}
        - alert: {{ .alert }}
          expr: |
            {{- tpl .expr $ | nindent 12}}
          labels:
            {{- range $key, $value := $.Values.monitoring.rules.alertLabels }}
            {{ $key }}: {{ tpl $value $ }}
            {{- end }}
            {{- with .labels}}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          annotations:
            app_version: {{ $.Chart.AppVersion }}
            chart_version: {{ $.Chart.Version }}
            {{- with .annotations }}
            {{- toYaml . | nindent 12}}
            {{- end}}
            {{- with $.Values.monitoring.rules.alertAnnotations }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        {{ end}}
{{- end -}}