{{ $dict := dict "ctx" . "component" "tracepoint" "memberlist" true }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "deep.resourceName" $dict }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "deep.labels" $dict | nindent 4 }}
  {{- with .Values.tracepoint.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  minReadySeconds: 10
{{- if not .Values.tracepoint.autoscaling.enabled }}
  replicas: {{ .Values.tracepoint.replicas }}
{{- end }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      {{- include "deep.selectorLabels" $dict | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        {{- include "deep.podLabels" $dict | nindent 8 }}
        {{- with .Values.deep.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.tracepoint.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-deep.yaml") . | sha256sum }}
        {{- with .Values.deep.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.tracepoint.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if or (.Values.tracepoint.priorityClassName) (.Values.global.priorityClassName) }}
      priorityClassName: {{ default .Values.tracepoint.priorityClassName .Values.global.priorityClassName }}
      {{- end }}
      serviceAccountName: {{ include "deep.serviceAccountName" . }}
      {{- with .Values.deep.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      enableServiceLinks: false
      {{- include "deep.tracepointImagePullSecrets" . | nindent 6 -}}
      {{- with .Values.tracepoint.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - args:
            - -target=tracepoint
            - -config.file=/conf/deep.yaml
            - -mem-ballast-size-mbs=1024
            {{- with .Values.tracepoint.extraArgs }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          image: {{ include "deep.imageReference" $dict }}
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          name: tracepoint
          ports:
            - containerPort: 7946
              name: http-memberlist
              protocol: TCP
            - containerPort: 3100
              name: http-metrics
          {{- with .Values.tracepoint.extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tracepoint.extraEnvFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.tracepoint.resources | nindent 12 }}
          {{- with .Values.deep.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deep.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /conf
              name: config
            - mountPath: /runtime-config
              name: runtime-config
            - mountPath: /var/deep
              name: deep-tracepoint-store
            {{- with .Values.tracepoint.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      terminationGracePeriodSeconds: {{ .Values.tracepoint.terminationGracePeriodSeconds }}
      {{- if ge (.Capabilities.KubeVersion.Minor|int) 19 }}
      {{- with .Values.tracepoint.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- tpl . $ | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- with .Values.tracepoint.affinity }}
      affinity:
        {{- tpl . $ | nindent 8 }}
      {{- end }}
      {{- with .Values.tracepoint.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tracepoint.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          {{- include "deep.configVolume" . | nindent 10 }}
        - name: runtime-config
          {{- include "deep.runtimeVolume" . | nindent 10 }}
        - name: deep-tracepoint-store
          emptyDir: {}
        {{- with .Values.tracepoint.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
