apiVersion: v1
kind: Service
metadata:
  name: {{ template "deep.resourceName" (dict "ctx" . "component" "tracepoint") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "deep.labels" (dict "ctx" . "component" "tracepoint") | nindent 4 }}
  {{- with .Values.tracepoint.service.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
    - name: http-metrics
      port: 3100
      protocol: TCP
      targetPort: 3100
    - name: grpc
      port: 9095
      protocol: TCP
      targetPort: 9095
      {{- if .Values.tracepoint.appProtocol.grpc }}
      appProtocol: {{ .Values.tracepoint.appProtocol.grpc }}
      {{- end }}
  selector:
    {{- include "deep.selectorLabels" (dict "ctx" . "component" "tracepoint" "memberlist" true) | nindent 4 }}
