name: Generate Docs

on:
  push:
    branches:
      - master

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  get_index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
      - name: upload index
        uses: actions/upload-artifact@v3
        with:
          name: helm_index
          path: index.yaml

  build_docs:
    needs: get_index
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - run: pip install helm_mkdocs mkdocs-material
      - run: |
          helm-mkdocs ./charts/deep -o docs_out/deep
          helm-mkdocs ./charts/deep-distributed -o docs_out/deep
      - run: cp README.md docs_out/index.md
      - run: mkdocs build
      - name: Download index
        uses: actions/download-artifact@v3
        with:
          name: helm_index
      - run: cp index.yaml docs_out/index.yaml
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1

