name: Generate Docs

on:
  push:
    branches:
      - master

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install helm_mkdocs mkdocs-material
      - run: |
          helm-mkdocs ./charts/deep -o docs_out/deep
          helm-mkdocs ./charts/deep-distributed -o docs_out/deep
      - run: cp README.md docs_out/index.md
      - run: mkdocs build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1

