on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: debug
        run: |
          ls -la
      - name: Helm Lint
        run: |
          helm lint ${GITHUB_WORKSPACE}/charts/deep-distributed
