name: Helm Unit Test

on:
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: helm plugin install https://github.com/helm-unittest/helm-unittest.git
      - name: Helm unittest
        run: |
          helm unittest -f unittests/*_test.yaml ${GITHUB_WORKSPACE}/charts/deep
          helm unittest -f unittests/*_test.yaml ${GITHUB_WORKSPACE}/charts/deep-distributed
