{{- $dict := dict "ctx" . "component" "gateway" -}}
{{- with .Values.gateway }}
{{- if and .enabled .basicAuth.enabled (not .basicAuth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "deep.resourceName" $dict }}
  labels:
    {{- include "deep.labels" $dict | nindent 4 }}
stringData:
  .htpasswd: |
    {{- tpl .basicAuth.htpasswd $dict.ctx | nindent 4 }}
{{- end }}
{{- end }}
